### ISSUE TITLE
Why the dependence on BenchmarkTools?

### ISSUE THREAD

**Issue by gdalle** [withbayes/Tapir.jl#105]
I looked for `@b` in the package and it only shows up in benchmarking or testing. Any reason to keep BenchmarkTools in the package's dependencies?

**Comment by gdalle** [comment]
Presumably the same goes for the Profile stdlib

**Comment by willtebbutt** [comment]
Good catch, must be an oversight on my part. Will deal with this at some point 👍

**Comment by willtebbutt** [comment]
> Presumably the same goes for the Profile stdlib

Where abouts in the code did you find the `Profile` stdlib dep? I can't seem to find it in the code.

**Comment by gdalle** [comment]
Adding Tapir to my test environment back when it wasn't registered happened after instantiation, and so I saw all the packages that were added to the manifest. The ones that struck me as out of place were Profile and BenchmarkTools, but maybe Profile was an indirect dependency (eg _of_ BenchmarkTools), I didn't double-check.

**Comment by willtebbutt** [comment]
Cool -- yeah, I think you're correct re Profile being an indirect dep of Tapir. Thanks for confirming.

**Comment by willtebbutt** [comment]
Resolved by #108 . Thanks for catching this @gdalle
