### ISSUE TITLE
Add a "getting started" early in the README

### ISSUE THREAD

**Issue by gdalle** [withbayes/Tapir.jl#135]
Right now you have to scroll all the way down the README to figure out how to use Tapir. Maybe you could add a small section where you point to DifferentiationInterface and give a syntax example with `AutoTapir()`?

https://github.com/JuliaRegistries/General/pull/105953 will be merged soon with Tapir v0.2 compat

**Comment by willtebbutt** [comment]
This is a good idea.

**Comment by willtebbutt** [comment]
Resolved by #145
