### ISSUE TITLE
Add tests for `CUDA.jl` array types

### ISSUE THREAD

**Issue by yebai** [withbayes/Tapir.jl#35]
Since we plan to support GPU from this new AD package, it would be good to start testing against some `CUDA.jl` functionalities early in the process. This should be similar to #29 for many cases, but on `CuArray` types instead of `Array`.

**Comment by willtebbutt** [comment]
Agreed. I'll need to get GPU CI set up, which I've done before, and isn't too much of a pain, but it'll take a few days I imagine.

**Comment by willtebbutt** [comment]
Resolved by #161 -- this has the very basics of a GPU pipeline (Tapir.jl knows about `CuArray`s, and knows how to differentiate through creating one with undefined elements).
